name: Setup Rust
description: Setup Rust toolchain with optional cross-compilation targets

inputs:
  targets:
    description: 'Comma-separated list of Rust targets to install (e.g., aarch64-apple-darwin,x86_64-apple-darwin)'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.targets }}

    - name: Add cargo bin to PATH (Unix)
      if: runner.os != 'Windows'
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash

    - name: Add cargo bin to PATH (Windows)
      if: runner.os == 'Windows'
      run: echo "$env:USERPROFILE\.cargo\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
      shell: pwsh

    # Use Strawberry Perl for OpenSSL build (MSYS2 Perl from Git Bash is incompatible)
    - name: Configure Perl for OpenSSL (Windows)
      if: runner.os == 'Windows'
      run: echo "PERL=C:\Strawberry\perl\bin\perl.exe" >> $GITHUB_ENV
      shell: bash

    # Cache compiled Rust dependencies (keyed on Cargo.lock, OS, rustc version).
    # Dramatically speeds up Windows builds where vendored OpenSSL takes ~10 min.
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "rust -> target"
        cache-on-failure: true
