// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'config.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `build_credential_with_key`, `commit`, `db`, `load_for_group`, `load_global`, `load_group`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `OpSession`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `crypto`, `rand`, `storage`

/// Extract the group ID from an MLS protocol message.
///
/// Useful for routing incoming messages to the right group before calling
/// `processMessage`. Returns an error if the message is not a protocol
/// message (i.e. it's a Welcome, GroupInfo, or KeyPackage).
Uint8List mlsMessageExtractGroupId({required List<int> messageBytes}) => RustLib
    .instance
    .api
    .crateApiEngineMlsMessageExtractGroupId(messageBytes: messageBytes);

/// Extract the epoch from an MLS protocol message.
///
/// Returns an error if the message is not a protocol message.
BigInt mlsMessageExtractEpoch({required List<int> messageBytes}) => RustLib
    .instance
    .api
    .crateApiEngineMlsMessageExtractEpoch(messageBytes: messageBytes);

/// Get the content type of an MLS protocol message as a string.
///
/// Returns one of: "application", "proposal", "commit".
/// Returns an error if the message is not a protocol message.
String mlsMessageContentType({required List<int> messageBytes}) => RustLib
    .instance
    .api
    .crateApiEngineMlsMessageContentType(messageBytes: messageBytes);

/// Reads the validity window out of a key package.
///
/// Pair this with `checkLifetimeAt` to judge a key package by a clock other
/// than the device's — a timestamp from a server, say — before offering it to
/// `addMembers`.
///
/// ⚠ **The device's own clock still gates this call.** Getting at the window
/// means validating the key package, and OpenMLS's validation checks
/// signatures, protocol version, extensions *and* the lifetime, that last one
/// against `SystemTime::now()` on this device. There is no way to ask it to
/// skip that from outside the crate. So a key package this device believes is
/// expired, or not yet valid, fails here and never yields its bounds: the pair
/// of functions can apply an authority stricter than the local clock, not
/// rescue a package the local clock has already rejected.
KeyPackageLifetime keyPackageLifetime({required List<int> keyPackageBytes}) =>
    RustLib.instance.api.crateApiEngineKeyPackageLifetime(
      keyPackageBytes: keyPackageBytes,
    );

/// Checks a validity window against a supplied instant instead of this
/// device's clock.
///
/// Takes the two bounds rather than key package bytes, so that this half of
/// the check has no dependency on the local clock at all: `keyPackageLifetime`
/// is the only way to read bounds *out of* a key package and it does consult
/// the local clock, but a caller that already holds bounds — from its own
/// directory, from an earlier reading, from a server that publishes them — can
/// apply this on its own.
///
/// The comparison is OpenMLS's (`Lifetime::validate_with_time`), not a
/// re-implementation, so the boundaries match what a peer will decide about
/// the same package: `notAfter` is exclusive — an instant equal to it counts
/// as expired — while `notBefore` is inclusive.
///
/// Returns an error only when `nowUnixSeconds` names no instant a calendar
/// could mean — anything past 9999-12-31T23:59:59Z. An instant outside the
/// window is a verdict, not an error, and below that cap every platform this
/// package ships for answers a given argument the same way.
///
/// That cap also catches the likeliest way to call this wrongly. Dart has no
/// `secondsSinceEpoch`, so a caller reaching for `DateTime` meets
/// `millisecondsSinceEpoch` first, and a present-day millisecond count is
/// roughly a thousand times too large — comfortably past the cap, so it fails
/// loudly here instead of returning a confident verdict about a date tens of
/// thousands of years out.
LifetimeVerdict checkLifetimeAt({
  required BigInt notBefore,
  required BigInt notAfter,
  required BigInt nowUnixSeconds,
}) => RustLib.instance.api.crateApiEngineCheckLifetimeAt(
  notBefore: notBefore,
  notAfter: notAfter,
  nowUnixSeconds: nowUnixSeconds,
);

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MlsEngine>>
abstract class MlsEngine implements RustOpaqueInterface {
  Future<AddMembersResult> addMembers({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
    required List<Uint8List> keyPackagesBytes,
  });

  Future<AddMembersResult> addMembersWithoutUpdate({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
    required List<Uint8List> keyPackagesBytes,
  });

  Future<void> clearPendingCommit({required List<int> groupIdBytes});

  Future<void> clearPendingProposals({required List<int> groupIdBytes});

  /// Close the engine, wiping the encryption key from memory and closing the
  /// database connection. After calling this, all operations will fail with
  /// "MlsEngine is closed". Idempotent — calling close on an already-closed
  /// engine is a no-op.
  Future<void> close();

  Future<CommitResult> commitToPendingProposals({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
  });

  /// Create a new MlsEngine backed by an encrypted database.
  ///
  /// # Arguments
  ///
  /// * `dbPath` — Database location.
  ///   - **Native**: file path for SQLCipher (e.g. `"path/to/mls.db"`).
  ///     Use `":memory:"` for an ephemeral in-memory database (destroyed on drop,
  ///     useful for tests). A `"file:…"` URI is rejected: the path it resolves
  ///     to cannot be recovered without parsing the URI, so such a database
  ///     would get neither owner-only permissions nor the lock file below.
  ///   - **WASM**: IndexedDB database name (e.g. `"mls_account_123"`).
  ///     `":memory:"` generates a unique random name per instance to match the
  ///     native ephemeral behavior.
  ///   - Tip: include an account identifier in the path to isolate data per user
  ///     (e.g. `"mls_{account_id}.db"` on native, `"mls_{account_id}"` on web).
  ///
  /// * `encryptionKey` — 32-byte AES-256 key that protects data at rest.
  ///   The caller is responsible for generating, storing, and providing this key.
  ///   Recommended pattern: generate a random key on first launch and persist it
  ///   in platform secure storage (e.g. Keychain on iOS/macOS, Android Keystore,
  ///   or `flutter_secure_storage`).
  ///
  /// # One engine per database file
  ///
  /// On native the database is locked exclusively. A second engine on the same
  /// file — another instance, isolate or process — fails with "Database is
  /// already open by another connection or process" rather than silently
  /// overwriting this one's group state. `MlsEngine.close` releases the
  /// lock; an overlapping opener waits out a five-second timeout first, so
  /// handing the file over during teardown still works.
  ///
  /// On Unix this is held partly by a lock file next to the database, named
  /// `<db_path>.lock`, which the engine creates and never deletes. An empty
  /// file beside the database is expected; deleting it while an engine is
  /// running removes the protection.
  ///
  /// Calls on one engine are safe to make concurrently: each runs its
  /// load → operate → save cycle under an engine-wide lock.
  static Future<MlsEngine> create({
    required String dbPath,
    required List<int> encryptionKey,
  }) => RustLib.instance.api.crateApiEngineMlsEngineCreate(
    dbPath: dbPath,
    encryptionKey: encryptionKey,
  );

  Future<CreateGroupResult> createGroup({
    required MlsGroupConfig config,
    required List<int> signerBytes,
    required List<int> credentialIdentity,
    required List<int> signerPublicKey,
    Uint8List? groupId,
    Uint8List? credentialBytes,
  });

  Future<CreateGroupResult> createGroupWithBuilder({
    required MlsGroupConfig config,
    required List<int> signerBytes,
    required List<int> credentialIdentity,
    required List<int> signerPublicKey,
    Uint8List? groupId,
    BigInt? lifetimeSeconds,
    List<MlsExtension>? groupContextExtensions,
    List<MlsExtension>? leafNodeExtensions,
    MlsCapabilities? capabilities,
    Uint8List? credentialBytes,
  });

  /// Builds a key package with OpenMLS's defaults for everything except the
  /// ciphersuite and the credential.
  ///
  /// Those defaults include the advertised capabilities, and the ciphersuite
  /// list inside them is every suite `supportedCiphersuites` returns — ten of
  /// them experimental post-quantum suites on provisional code points. A peer
  /// reading this key package may therefore pick one of those for a group.
  ///
  /// To advertise a narrower set, or to change the lifetime, mark the package
  /// last-resort, or attach extensions, use `createKeyPackageWithOptions`
  /// instead: `KeyPackageOptions.capabilities` is where the ciphersuite list
  /// goes.
  Future<KeyPackageResult> createKeyPackage({
    required MlsCiphersuite ciphersuite,
    required List<int> signerBytes,
    required List<int> credentialIdentity,
    required List<int> signerPublicKey,
    Uint8List? credentialBytes,
  });

  /// Builds a key package, overriding the defaults `createKeyPackage` leaves
  /// alone.
  ///
  /// Every field of `KeyPackageOptions` is optional and an unset one keeps
  /// OpenMLS's default. `capabilities` is the one with a wire consequence:
  /// setting `MlsCapabilities.ciphersuites` to an explicit list of raw code
  /// points is the only way to stop a key package advertising every suite
  /// this provider supports, experimental ones included.
  Future<KeyPackageResult> createKeyPackageWithOptions({
    required MlsCiphersuite ciphersuite,
    required List<int> signerBytes,
    required List<int> credentialIdentity,
    required List<int> signerPublicKey,
    required KeyPackageOptions options,
    Uint8List? credentialBytes,
  });

  Future<CreateMessageResult> createMessage({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
    required List<int> message,
    Uint8List? aad,
  });

  Future<void> deleteGroup({required List<int> groupIdBytes});

  Future<void> deleteKeyPackage({required List<int> keyPackageRefBytes});

  Future<MlsGroupContextInfo> exportGroupContext({
    required List<int> groupIdBytes,
  });

  Future<Uint8List> exportGroupInfo({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
  });

  Future<Uint8List> exportRatchetTree({required List<int> groupIdBytes});

  Future<Uint8List> exportSecret({
    required List<int> groupIdBytes,
    required String label,
    required List<int> context,
    required int keyLength,
  });

  /// Derives a secret from the epoch a Welcome invites this client into,
  /// **without joining the group**.
  ///
  /// This is `exportSecret` one step earlier: same derivation, same
  /// `label`/`context`/`keyLength` meaning, but reachable while the
  /// invitation is still only an invitation. It is what lets a client agree
  /// a key with the inviter — or prove to a third party that it can read the
  /// epoch — before it decides whether to accept.
  ///
  /// Like `inspectWelcome`, this writes nothing, and that is load-bearing
  /// rather than incidental. Processing a Welcome consumes the key package
  /// it was addressed to: OpenMLS deletes it from storage unless it is
  /// marked last-resort. Here that delete lands in this call's snapshot and
  /// is discarded with it, because neither this function nor `inspectWelcome`
  /// commits — so a later `joinGroupFromWelcome` on the same Welcome still
  /// finds its key package. Committing from either would silently burn the
  /// invitation.
  ///
  /// The secret comes from the unverified group info in the Welcome. The
  /// confirmation tag is only checked when the Welcome is staged into a
  /// group, which happens in `joinGroupFromWelcome` and not here.
  ///
  /// It sees exactly the storage the real join sees:
  /// `joinGroupFromWelcome` loads the same global scope, and pre-shared keys
  /// live in it (they are stored ungrouped, like key packages and signature
  /// keys). So a Welcome that carries PSKs resolves them here or fails here
  /// for the same reason it would there — this function is never the narrower
  /// of the two.
  Future<Uint8List> exportWelcomeSecret({
    required MlsGroupConfig config,
    required List<int> welcomeBytes,
    required String label,
    required List<int> context,
    required int keyLength,
  });

  Future<CommitResult> flexibleCommit({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
    required FlexibleCommitOptions options,
  });

  Future<Uint8List?> getPastResumptionPsk({
    required List<int> groupIdBytes,
    required BigInt epoch,
  });

  Future<MlsCiphersuite> groupCiphersuite({required List<int> groupIdBytes});

  Future<GroupConfigurationResult> groupConfiguration({
    required List<int> groupIdBytes,
  });

  Future<Uint8List> groupConfirmationTag({required List<int> groupIdBytes});

  Future<Uint8List> groupCredential({required List<int> groupIdBytes});

  Future<BigInt> groupEpoch({required List<int> groupIdBytes});

  Future<Uint8List> groupEpochAuthenticator({required List<int> groupIdBytes});

  Future<Uint8List> groupExtensions({required List<int> groupIdBytes});

  Future<bool> groupHasPendingProposals({required List<int> groupIdBytes});

  Future<Uint8List> groupId({required List<int> groupIdBytes});

  Future<bool> groupIsActive({required List<int> groupIdBytes});

  Future<MlsMemberInfo?> groupMemberAt({
    required List<int> groupIdBytes,
    required int leafIndex,
  });

  Future<int?> groupMemberLeafIndex({
    required List<int> groupIdBytes,
    required List<int> credentialBytes,
  });

  Future<List<MlsMemberInfo>> groupMembers({required List<int> groupIdBytes});

  Future<int> groupOwnIndex({required List<int> groupIdBytes});

  Future<MlsLeafNodeInfo> groupOwnLeafNode({required List<int> groupIdBytes});

  Future<List<MlsPendingProposalInfo>> groupPendingProposals({
    required List<int> groupIdBytes,
  });

  Future<WelcomeInspectResult> inspectWelcome({
    required MlsGroupConfig config,
    required List<int> welcomeBytes,
  });

  /// Check whether this engine has been closed.
  bool isClosed();

  Future<ExternalJoinResult> joinGroupExternalCommit({
    required MlsGroupConfig config,
    required List<int> groupInfoBytes,
    Uint8List? ratchetTreeBytes,
    required List<int> signerBytes,
    required List<int> credentialIdentity,
    required List<int> signerPublicKey,
    Uint8List? credentialBytes,
  });

  Future<ExternalJoinResult> joinGroupExternalCommitV2({
    required MlsGroupConfig config,
    required List<int> groupInfoBytes,
    Uint8List? ratchetTreeBytes,
    required List<int> signerBytes,
    required List<int> credentialIdentity,
    required List<int> signerPublicKey,
    Uint8List? aad,
    required bool skipLifetimeValidation,
    Uint8List? credentialBytes,
  });

  Future<JoinGroupResult> joinGroupFromWelcome({
    required MlsGroupConfig config,
    required List<int> welcomeBytes,
    Uint8List? ratchetTreeBytes,
    required List<int> signerBytes,
  });

  Future<JoinGroupResult> joinGroupFromWelcomeWithOptions({
    required MlsGroupConfig config,
    required List<int> welcomeBytes,
    Uint8List? ratchetTreeBytes,
    required List<int> signerBytes,
    required bool skipLifetimeValidation,
  });

  Future<LeaveGroupResult> leaveGroup({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
  });

  Future<LeaveGroupResult> leaveGroupViaSelfRemove({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
  });

  Future<void> mergePendingCommit({required List<int> groupIdBytes});

  Future<ProcessedMessageResult> processMessage({
    required List<int> groupIdBytes,
    required List<int> messageBytes,
  });

  Future<ProcessedMessageInspectResult> processMessageWithInspect({
    required List<int> groupIdBytes,
    required List<int> messageBytes,
  });

  Future<ProposalResult> proposeAdd({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
    required List<int> keyPackageBytes,
  });

  Future<ProposalResult> proposeCustomProposal({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
    required int proposalType,
    required List<int> payload,
  });

  Future<ProposalResult> proposeExternalPsk({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
    required List<int> pskId,
    required List<int> pskNonce,
  });

  Future<ProposalResult> proposeGroupContextExtensions({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
    required List<MlsExtension> extensions,
  });

  Future<ProposalResult> proposeRemove({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
    required int memberIndex,
  });

  Future<ProposalResult> proposeRemoveMemberByCredential({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
    required List<int> credentialBytes,
  });

  Future<ProposalResult> proposeSelfUpdate({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
    MlsCapabilities? leafNodeCapabilities,
    List<MlsExtension>? leafNodeExtensions,
  });

  /// Proposes a self-update that also rotates this member's signature key.
  ///
  /// The proposal form of `selfUpdateWithNewSigner`: the same key rotation,
  /// queued as a proposal instead of committed, so it can be carried by
  /// somebody else's commit.
  ///
  /// Two signers are needed because the message and its payload are
  /// authenticated against different keys. The envelope is signed with
  /// `oldSignerBytes`, since this member's leaf in the group tree still
  /// carries the old signature key at the time the proposal is sent; the new
  /// leaf inside the proposal is self-signed by `newSignerBytes` so that it
  /// verifies against the `signatureKey` it announces. Both must therefore be
  /// real key pairs with private keys.
  ///
  /// Upstream requires that a credential set in the leaf-node parameters
  /// equal the new signer's credential. This wrapper cannot violate that: it
  /// builds leaf-node parameters from `leafNodeCapabilities` and
  /// `leafNodeExtensions` only and never sets a credential there, so the
  /// credential built from `newCredentialIdentity` /
  /// `newSignerPublicKey` / `newCredentialBytes` is always the one that gets
  /// folded in.
  ///
  /// The new signer is stored before the proposal is created, matching
  /// `selfUpdateWithNewSigner`, so the key is available to sign with once the
  /// proposal is committed. Fails if a commit is already pending.
  ///
  /// Availability rests on this crate not enabling openmls's
  /// `virtual-clients-draft` feature. Upstream gates this function on
  /// `not(virtual-clients-draft)`, its own `test-utils`, or `test` — and that
  /// `test-utils` was deliberately dropped from the shipped binary in 3.0.0,
  /// so `not(virtual-clients-draft)` is the only arm holding it open here.
  Future<ProposalResult> proposeSelfUpdateWithNewSigner({
    required List<int> groupIdBytes,
    required List<int> oldSignerBytes,
    required List<int> newSignerBytes,
    required List<int> newCredentialIdentity,
    required List<int> newSignerPublicKey,
    Uint8List? newCredentialBytes,
    MlsCapabilities? leafNodeCapabilities,
    List<MlsExtension>? leafNodeExtensions,
  });

  Future<CommitResult> removeMembers({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
    required List<int> memberIndices,
  });

  Future<void> removePendingProposal({
    required List<int> groupIdBytes,
    required List<int> proposalRefBytes,
  });

  /// Return the database schema version.
  ///
  /// After a successful `create()`, this is always `LATEST_SCHEMA_VERSION`.
  /// Useful for diagnostics and debugging migration issues.
  int schemaVersion();

  Future<CommitResult> selfUpdate({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
  });

  Future<CommitResult> selfUpdateWithNewSigner({
    required List<int> groupIdBytes,
    required List<int> oldSignerBytes,
    required List<int> newSignerBytes,
    required List<int> newCredentialIdentity,
    required List<int> newSignerPublicKey,
    Uint8List? newCredentialBytes,
  });

  Future<void> setConfiguration({
    required List<int> groupIdBytes,
    required MlsGroupConfig config,
  });

  Future<AddMembersResult> swapMembers({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
    required List<int> removeIndices,
    required List<Uint8List> addKeyPackagesBytes,
  });

  Future<CommitResult> updateGroupContextExtensions({
    required List<int> groupIdBytes,
    required List<int> signerBytes,
    required List<MlsExtension> extensions,
  });
}

class AddMembersResult {
  final Uint8List commit;
  final Uint8List welcome;
  final Uint8List? groupInfo;

  const AddMembersResult({
    required this.commit,
    required this.welcome,
    this.groupInfo,
  });

  @override
  int get hashCode => commit.hashCode ^ welcome.hashCode ^ groupInfo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddMembersResult &&
          runtimeType == other.runtimeType &&
          commit == other.commit &&
          welcome == other.welcome &&
          groupInfo == other.groupInfo;
}

class CommitResult {
  final Uint8List commit;
  final Uint8List? welcome;
  final Uint8List? groupInfo;

  const CommitResult({required this.commit, this.welcome, this.groupInfo});

  @override
  int get hashCode => commit.hashCode ^ welcome.hashCode ^ groupInfo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommitResult &&
          runtimeType == other.runtimeType &&
          commit == other.commit &&
          welcome == other.welcome &&
          groupInfo == other.groupInfo;
}

class CreateGroupResult {
  final Uint8List groupId;

  const CreateGroupResult({required this.groupId});

  @override
  int get hashCode => groupId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateGroupResult &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId;
}

class CreateMessageResult {
  final Uint8List ciphertext;

  const CreateMessageResult({required this.ciphertext});

  @override
  int get hashCode => ciphertext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateMessageResult &&
          runtimeType == other.runtimeType &&
          ciphertext == other.ciphertext;
}

class ExternalJoinResult {
  final Uint8List groupId;
  final Uint8List commit;
  final Uint8List? groupInfo;

  const ExternalJoinResult({
    required this.groupId,
    required this.commit,
    this.groupInfo,
  });

  @override
  int get hashCode => groupId.hashCode ^ commit.hashCode ^ groupInfo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExternalJoinResult &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          commit == other.commit &&
          groupInfo == other.groupInfo;
}

class GroupConfigurationResult {
  final MlsCiphersuite ciphersuite;
  final MlsWireFormatPolicy wireFormatPolicy;
  final int paddingSize;
  final int senderRatchetMaxOutOfOrder;
  final int senderRatchetMaxForwardDistance;

  const GroupConfigurationResult({
    required this.ciphersuite,
    required this.wireFormatPolicy,
    required this.paddingSize,
    required this.senderRatchetMaxOutOfOrder,
    required this.senderRatchetMaxForwardDistance,
  });

  @override
  int get hashCode =>
      ciphersuite.hashCode ^
      wireFormatPolicy.hashCode ^
      paddingSize.hashCode ^
      senderRatchetMaxOutOfOrder.hashCode ^
      senderRatchetMaxForwardDistance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupConfigurationResult &&
          runtimeType == other.runtimeType &&
          ciphersuite == other.ciphersuite &&
          wireFormatPolicy == other.wireFormatPolicy &&
          paddingSize == other.paddingSize &&
          senderRatchetMaxOutOfOrder == other.senderRatchetMaxOutOfOrder &&
          senderRatchetMaxForwardDistance ==
              other.senderRatchetMaxForwardDistance;
}

class JoinGroupResult {
  final Uint8List groupId;

  const JoinGroupResult({required this.groupId});

  @override
  int get hashCode => groupId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JoinGroupResult &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId;
}

/// The window during which a key package may be used, as seconds since the
/// Unix epoch.
class KeyPackageLifetime {
  /// Start of the window. A client must not use the key package before this
  /// instant; an instant equal to it is already inside the window.
  final BigInt notBefore;

  /// End of the window. A client must not use the key package at or after
  /// this instant.
  final BigInt notAfter;

  const KeyPackageLifetime({required this.notBefore, required this.notAfter});

  @override
  int get hashCode => notBefore.hashCode ^ notAfter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPackageLifetime &&
          runtimeType == other.runtimeType &&
          notBefore == other.notBefore &&
          notAfter == other.notAfter;
}

class KeyPackageResult {
  final Uint8List keyPackageBytes;

  const KeyPackageResult({required this.keyPackageBytes});

  @override
  int get hashCode => keyPackageBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPackageResult &&
          runtimeType == other.runtimeType &&
          keyPackageBytes == other.keyPackageBytes;
}

class LeaveGroupResult {
  final Uint8List message;

  const LeaveGroupResult({required this.message});

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LeaveGroupResult &&
          runtimeType == other.runtimeType &&
          message == other.message;
}

/// Whether a validity window admits some instant, and OpenMLS's reason when it
/// does not.
class LifetimeVerdict {
  /// True when the instant falls inside the window.
  final bool valid;

  /// Why not, when `valid` is false. Null when it is true.
  final String? reason;

  const LifetimeVerdict({required this.valid, this.reason});

  @override
  int get hashCode => valid.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LifetimeVerdict &&
          runtimeType == other.runtimeType &&
          valid == other.valid &&
          reason == other.reason;
}

class ProcessedMessageInspectResult {
  final ProcessedMessageType messageType;
  final int? senderIndex;
  final BigInt epoch;
  final Uint8List? applicationMessage;
  final StagedCommitInfo? stagedCommitInfo;
  final MlsProposalType? proposalType;

  const ProcessedMessageInspectResult({
    required this.messageType,
    this.senderIndex,
    required this.epoch,
    this.applicationMessage,
    this.stagedCommitInfo,
    this.proposalType,
  });

  @override
  int get hashCode =>
      messageType.hashCode ^
      senderIndex.hashCode ^
      epoch.hashCode ^
      applicationMessage.hashCode ^
      stagedCommitInfo.hashCode ^
      proposalType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessedMessageInspectResult &&
          runtimeType == other.runtimeType &&
          messageType == other.messageType &&
          senderIndex == other.senderIndex &&
          epoch == other.epoch &&
          applicationMessage == other.applicationMessage &&
          stagedCommitInfo == other.stagedCommitInfo &&
          proposalType == other.proposalType;
}

class ProcessedMessageResult {
  final ProcessedMessageType messageType;
  final int? senderIndex;
  final BigInt epoch;
  final Uint8List? applicationMessage;
  final bool hasStagedCommit;
  final bool hasProposal;
  final MlsProposalType? proposalType;

  const ProcessedMessageResult({
    required this.messageType,
    this.senderIndex,
    required this.epoch,
    this.applicationMessage,
    required this.hasStagedCommit,
    required this.hasProposal,
    this.proposalType,
  });

  @override
  int get hashCode =>
      messageType.hashCode ^
      senderIndex.hashCode ^
      epoch.hashCode ^
      applicationMessage.hashCode ^
      hasStagedCommit.hashCode ^
      hasProposal.hashCode ^
      proposalType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessedMessageResult &&
          runtimeType == other.runtimeType &&
          messageType == other.messageType &&
          senderIndex == other.senderIndex &&
          epoch == other.epoch &&
          applicationMessage == other.applicationMessage &&
          hasStagedCommit == other.hasStagedCommit &&
          hasProposal == other.hasProposal &&
          proposalType == other.proposalType;
}

class ProposalResult {
  final Uint8List proposalMessage;

  const ProposalResult({required this.proposalMessage});

  @override
  int get hashCode => proposalMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProposalResult &&
          runtimeType == other.runtimeType &&
          proposalMessage == other.proposalMessage;
}
