// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decrypt_value`, `encrypt_value`, `hex_string`, `poc_db_read`, `poc_db_write`

/// Store a key-value pair, load it into a sync HashMap, then write back.
/// Proves the pattern: async DB write → sync HashMap op → async DB write.
Future<Uint8List> pocStoreAndLoad({
  required String key,
  required List<int> value,
}) =>
    RustLib.instance.api.crateApiWasmPocPocStoreAndLoad(key: key, value: value);

/// Full roundtrip test: write → sync transform → read back → verify.
Future<String> pocRoundtripTest() =>
    RustLib.instance.api.crateApiWasmPocPocRoundtripTest();

/// Encrypted roundtrip test:
/// 1. Generate AES-256-GCM key
/// 2. Encrypt plaintext → write encrypted blob to DB
/// 3. Read raw bytes from DB (this is what you see in DevTools — gibberish)
/// 4. Decrypt → verify matches original
///
/// Returns a report with the raw encrypted hex (for visual inspection in DevTools).
Future<String> pocEncryptedRoundtrip({required List<int> encryptionKey}) =>
    RustLib.instance.api.crateApiWasmPocPocEncryptedRoundtrip(
      encryptionKey: encryptionKey,
    );

/// Test that decryption with the wrong key fails.
Future<String> pocWrongKeyTest({
  required List<int> correctKey,
  required List<int> wrongKey,
}) => RustLib.instance.api.crateApiWasmPocPocWrongKeyTest(
  correctKey: correctKey,
  wrongKey: wrongKey,
);
